name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v3
        name: Install Python ${{ matrix.version }}
        with:
          python-version: ${{ matrix.version }}
          cache: "pip"

      - name: Run nox
        run: |
          nox -s=tests-${{ matrix.version }}
        shell: bash
